import sqlite3

conn = sqlite3.connect('website_audit.db')
c = conn.cursor()

# Clear existing data
c.execute('DELETE FROM page_scores')

pages = [
    {
        'page_id': 12, 'page_name': 'Homepage', 'url': 'https://suriota.com/',
        'design_score': 20, 'mobile_score': 12, 'perf_score': 8, 'seo_score': 15, 'a11y_score': 7, 'content_score': 8, 'total_score': 70,
        'heading_h1': 'Homepage | Next Gen. Industrial Partner',
        'heading_issues': 'Duplicate H1: entry-title + elementor heading',
        'missing_alt_count': 3,
        'meta_title': 'Suriota - Surya Inovasi Prioritas', 'meta_title_length': 39,
        'meta_desc': 'PT Surya Inovasi Prioritas atau Suriota merupakan sebuah perusahaan yang bergerak di Technology Engineering Service berlokasi di Batam.', 'meta_desc_length': 132,
        'schema_types': 'BreadcrumbList,Organization,WebPage,WebSite',
        'console_errors': 2,
        'critical_issues': 'Slow load: 8785ms; Tawk.to CORS error',
        'warnings': 'Duplicate H1; 3 images missing alt; Meta desc could be more compelling; Only 259 words',
        'recommendations': 'Fix duplicate H1 by hiding entry-title; Add alt text to surge-eco-poster, modbus-poster, Porto.jpg; Expand homepage content to 400+ words; Optimize images',
        'screenshots': 'screenshots/audit-2026-05-18/'
    },
    {
        'page_id': 29, 'page_name': 'About Us', 'url': 'https://suriota.com/about-us/',
        'design_score': 22, 'mobile_score': 13, 'perf_score': 10, 'seo_score': 12, 'a11y_score': 8, 'content_score': 8, 'total_score': 73,
        'heading_h1': 'About Us | About SURIOTA',
        'heading_issues': 'Duplicate H1; Empty H2/H3 tags',
        'missing_alt_count': 0,
        'meta_title': 'About Us - Suriota', 'meta_title_length': 19,
        'meta_desc': 'About SURIOTA Next Gen. Industrial Partner — Industrial IoT & System Integration in Batam, Indonesia 01 / VISION...', 'meta_desc_length': 330,
        'schema_types': 'BreadcrumbList,Organization,WebPage,WebSite',
        'console_errors': 2,
        'critical_issues': 'Slow load: 4715ms; Meta desc 330 chars (way too long); Tawk.to CORS error',
        'warnings': 'Duplicate H1; Meta description 330 chars (max 160); Empty heading tags; Only 276 words',
        'recommendations': 'Fix duplicate H1; Truncate meta desc to 150-160 chars; Remove empty heading tags; Add more content',
        'screenshots': 'screenshots/audit-2026-05-18/'
    },
    {
        'page_id': 376, 'page_name': 'Tentang', 'url': 'https://suriota.com/tentang/',
        'design_score': 5, 'mobile_score': 5, 'perf_score': 5, 'seo_score': 5, 'a11y_score': 5, 'content_score': 5, 'total_score': 30,
        'heading_h1': 'Halaman tidak dapat ditemukan.',
        'heading_issues': 'Page returns 404',
        'missing_alt_count': 0,
        'meta_title': 'Laman tidak ditemukan – Suriota', 'meta_title_length': 37,
        'meta_desc': None, 'meta_desc_length': 0,
        'schema_types': 'None',
        'console_errors': 2,
        'critical_issues': 'PAGE NOT FOUND (404); Page exists in WP but not accessible',
        'warnings': 'Page is published but returns 404; Very old (2024-08-11); Likely slug/permalink issue',
        'recommendations': 'Investigate permalink/slug; Redirect to About Us or fix page; Remove from nav if dead',
        'screenshots': 'screenshots/audit-2026-05-18/'
    },
    {
        'page_id': 33, 'page_name': 'Desain Grafis', 'url': 'https://suriota.com/desain-grafis/',
        'design_score': 15, 'mobile_score': 10, 'perf_score': 10, 'seo_score': 10, 'a11y_score': 7, 'content_score': 6, 'total_score': 58,
        'heading_h1': 'Desain Grafis | DESAIN GRAFIS',
        'heading_issues': 'Duplicate H1; Very short title (23 chars)',
        'missing_alt_count': 0,
        'meta_title': 'Desain Grafis - Suriota', 'meta_title_length': 23,
        'meta_desc': 'DESAIN GRAFIS Mewujudkan Visi Anda dengan Desain Grafis Memukau dari Suriota...', 'meta_desc_length': 380,
        'schema_types': 'BreadcrumbList,Organization,WebPage,WebSite',
        'console_errors': 2,
        'critical_issues': 'Slow load: 6545ms; Meta desc 380 chars (too long); Title too short',
        'warnings': 'Duplicate H1; Title only 23 chars; Description 380 chars; Low content (1644 chars)',
        'recommendations': 'Rewrite title to 50-60 chars; Truncate meta desc; Merge with main service or improve content',
        'screenshots': 'screenshots/audit-cluster2-2026-05-18/'
    },
    {
        'page_id': 35, 'page_name': 'Automation', 'url': 'https://suriota.com/automation/',
        'design_score': 23, 'mobile_score': 13, 'perf_score': 10, 'seo_score': 20, 'a11y_score': 8, 'content_score': 8, 'total_score': 82,
        'heading_h1': 'Automation Services | Automation & IoT Services',
        'heading_issues': 'Duplicate H1',
        'missing_alt_count': 0,
        'meta_title': 'Industrial Automation & IoT Services | SURIOTA SCADA PLC', 'meta_title_length': 60,
        'meta_desc': 'PLC, SCADA, IIoT integration & SURGE platform for Industry 4.0. SURIOTA delivers industrial automation solutions across Indonesia.', 'meta_desc_length': 134,
        'schema_types': 'BreadcrumbList,Organization,WebPage,WebSite,Service,FAQPage',
        'console_errors': 2,
        'critical_issues': 'Duplicate H1; Tawk.to CORS error',
        'warnings': 'Duplicate H1; Good schema (Service + FAQPage)',
        'recommendations': 'Fix duplicate H1; Keep meta as-is (good length)',
        'screenshots': 'screenshots/audit-cluster2-2026-05-18/'
    },
    {
        'page_id': 37, 'page_name': 'Electrical', 'url': 'https://suriota.com/electrical/',
        'design_score': 22, 'mobile_score': 12, 'perf_score': 3, 'seo_score': 20, 'a11y_score': 8, 'content_score': 8, 'total_score': 73,
        'heading_h1': 'Electrical Services | Electrical Services',
        'heading_issues': 'Duplicate H1',
        'missing_alt_count': 0,
        'meta_title': 'Industrial Electrical Engineering Services Batam | SURIOTA', 'meta_title_length': 58,
        'meta_desc': 'Panel installation, power distribution, commissioning & testing per SNI, IEC, PUIL.', 'meta_desc_length': 159,
        'schema_types': 'BreadcrumbList,Organization,WebPage,WebSite,Service,FAQPage',
        'console_errors': 2,
        'critical_issues': 'EXTREMELY SLOW: 31686ms (31.7 seconds!); Duplicate H1; Tawk.to CORS',
        'warnings': 'Load time 31.7s - critical performance issue; Duplicate H1',
        'recommendations': 'URGENT: Investigate why Electrical loads in 31s (image? script?); Fix duplicate H1; This is a revenue-critical page',
        'screenshots': 'screenshots/audit-cluster2-2026-05-18/'
    },
    {
        'page_id': 39, 'page_name': 'Renewable Energy', 'url': 'https://suriota.com/renewable-energy/',
        'design_score': 22, 'mobile_score': 12, 'perf_score': 8, 'seo_score': 20, 'a11y_score': 8, 'content_score': 8, 'total_score': 78,
        'heading_h1': 'Renewable Energy Services | Renewable Energy Services',
        'heading_issues': 'Duplicate H1',
        'missing_alt_count': 0,
        'meta_title': 'Renewable Energy & Solar Panel Services | SURIOTA Indonesia', 'meta_title_length': 60,
        'meta_desc': 'Solar PV, hybrid PLTS-PLTB, energy audits & EPC. SURIOTA delivers renewable energy solutions.', 'meta_desc_length': 136,
        'schema_types': 'BreadcrumbList,Organization,WebPage,WebSite,Service,FAQPage',
        'console_errors': 2,
        'critical_issues': 'Slow load: 10908ms; Duplicate H1',
        'warnings': 'Duplicate H1; Load time 10.9s',
        'recommendations': 'Fix duplicate H1; Optimize page load (likely large images)',
        'screenshots': 'screenshots/audit-cluster2-2026-05-18/'
    },
    {
        'page_id': 41, 'page_name': 'Teknologi Informasi', 'url': 'https://suriota.com/teknologi-informasi/',
        'design_score': 18, 'mobile_score': 10, 'perf_score': 7, 'seo_score': 12, 'a11y_score': 7, 'content_score': 6, 'total_score': 60,
        'heading_h1': 'Teknologi Informasi | TEKNOLOGI INFORMASI',
        'heading_issues': 'Duplicate H1; Very short title (29 chars)',
        'missing_alt_count': 0,
        'meta_title': 'Teknologi Informasi - Suriota', 'meta_title_length': 29,
        'meta_desc': 'TEKNOLOGI INFORMASI Layanan Teknologi Informasi Terbaik di Suriota...', 'meta_desc_length': 419,
        'schema_types': 'BreadcrumbList,Organization,WebPage,WebSite',
        'console_errors': 2,
        'critical_issues': 'Slow load: 12557ms; Meta desc 419 chars (too long); Title too short',
        'warnings': 'Duplicate H1; Title 29 chars; Desc 419 chars; Thin content',
        'recommendations': 'Rewrite title to 50-60 chars; Truncate meta desc; Expand content significantly',
        'screenshots': 'screenshots/audit-cluster2-2026-05-18/'
    },
    {
        'page_id': 945, 'page_name': 'Water Treatment', 'url': 'https://suriota.com/water-treatment/',
        'design_score': 22, 'mobile_score': 13, 'perf_score': 10, 'seo_score': 20, 'a11y_score': 8, 'content_score': 8, 'total_score': 81,
        'heading_h1': 'Water Treatment Services',
        'heading_issues': 'Only 1 H1 - good!',
        'missing_alt_count': 0,
        'meta_title': 'Water Treatment & Wastewater Services | SURIOTA Indonesia', 'meta_title_length': 58,
        'meta_desc': 'Industrial water treatment, wastewater processing & IoT monitoring.', 'meta_desc_length': 134,
        'schema_types': 'BreadcrumbList,Organization,WebPage,WebSite,Service,FAQPage',
        'console_errors': 2,
        'critical_issues': 'Slow load: 4794ms; Tawk.to CORS',
        'warnings': 'Only 1 H1 (good!); Good meta lengths; Good schema',
        'recommendations': 'Optimize images to reduce load time; Keep structure as reference for other pages',
        'screenshots': 'screenshots/audit-cluster2-2026-05-18/'
    },
    {
        'page_id': 934, 'page_name': 'Modbus Gateway', 'url': 'https://suriota.com/modbus-gateway/',
        'design_score': 5, 'mobile_score': 5, 'perf_score': 5, 'seo_score': 5, 'a11y_score': 5, 'content_score': 5, 'total_score': 30,
        'heading_h1': 'Halaman tidak dapat ditemukan.',
        'heading_issues': 'PAGE NOT FOUND (404)',
        'missing_alt_count': 0,
        'meta_title': 'Laman tidak ditemukan – Suriota', 'meta_title_length': 37,
        'meta_desc': None, 'meta_desc_length': 0,
        'schema_types': 'None',
        'console_errors': 2,
        'critical_issues': 'PAGE NOT FOUND (404); Page exists in Elementor but not accessible; Load time 10666ms',
        'warnings': 'Page is published in WP/Elementor but returns 404; URL slug may have changed',
        'recommendations': 'CRITICAL: Fix permalink/slug for Modbus Gateway; This is a flagship product page',
        'screenshots': 'screenshots/audit-cluster3-2026-05-18/'
    },
    {
        'page_id': 929, 'page_name': 'Waste Water Loger', 'url': 'https://suriota.com/waste-water-loger/',
        'design_score': 5, 'mobile_score': 5, 'perf_score': 5, 'seo_score': 5, 'a11y_score': 5, 'content_score': 5, 'total_score': 30,
        'heading_h1': 'Halaman tidak dapat ditemukan.',
        'heading_issues': 'PAGE NOT FOUND (404)',
        'missing_alt_count': 0,
        'meta_title': 'Laman tidak ditemukan – Suriota', 'meta_title_length': 37,
        'meta_desc': None, 'meta_desc_length': 0,
        'schema_types': 'None',
        'console_errors': 2,
        'critical_issues': 'PAGE NOT FOUND (404); Page exists in Elementor but not accessible',
        'warnings': 'Page is published in WP/Elementor but returns 404',
        'recommendations': 'CRITICAL: Fix permalink/slug for Waste Water Loger',
        'screenshots': 'screenshots/audit-cluster3-2026-05-18/'
    },
    {
        'page_id': 1542, 'page_name': 'SURGE-Energy Mapping', 'url': 'https://suriota.com/surge-energy-mapping/',
        'design_score': 23, 'mobile_score': 12, 'perf_score': 7, 'seo_score': 18, 'a11y_score': 5, 'content_score': 10, 'total_score': 75,
        'heading_h1': 'SURGE Energy Mapping',
        'heading_issues': 'Good single H1',
        'missing_alt_count': 1,
        'meta_title': 'SURGE-Energy Mapping - Suriota', 'meta_title_length': 30,
        'meta_desc': 'SaaS · Energy Monitoring99.9% Uptime SLA SURGE-Energy Mapping Built For Multi-location...', 'meta_desc_length': 453,
        'schema_types': 'FAQPage',
        'console_errors': 2,
        'critical_issues': 'Slow load: 12444ms; Meta desc 453 chars (too long); Title too short (30 chars); 1 image missing alt',
        'warnings': 'Title 30 chars; Desc 453 chars; Missing alt on product image; Load time 12.4s',
        'recommendations': 'Expand title to 50-60 chars; Truncate meta desc to 150-160; Add alt text to product image; Optimize load',
        'screenshots': 'screenshots/audit-cluster3-2026-05-18/'
    },
    {
        'page_id': 1546, 'page_name': 'SURGE-Vessel Tracking', 'url': 'https://suriota.com/surge-vessel-tracking/',
        'design_score': 23, 'mobile_score': 12, 'perf_score': 7, 'seo_score': 18, 'a11y_score': 5, 'content_score': 10, 'total_score': 75,
        'heading_h1': 'SURGE Vessel Tracking',
        'heading_issues': 'Good single H1',
        'missing_alt_count': 1,
        'meta_title': 'SURGE-Vessel Tracking - Suriota', 'meta_title_length': 31,
        'meta_desc': 'SaaS · Vessel Tracking99.9% Uptime SLA SURGE-Vessel Tracking Built For Fleet tracking...', 'meta_desc_length': 429,
        'schema_types': 'FAQPage',
        'console_errors': 2,
        'critical_issues': 'Slow load: 14659ms; Meta desc 429 chars; Title 31 chars; 1 image missing alt',
        'warnings': 'Title 31 chars; Desc 429 chars; Missing alt; Load time 14.7s',
        'recommendations': 'Expand title; Truncate meta desc; Add alt text; Optimize load',
        'screenshots': 'screenshots/audit-cluster3-2026-05-18/'
    },
    {
        'page_id': 1547, 'page_name': 'SURGE-Water Analytic', 'url': 'https://suriota.com/surge-water-analytic/',
        'design_score': 23, 'mobile_score': 12, 'perf_score': 7, 'seo_score': 18, 'a11y_score': 5, 'content_score': 10, 'total_score': 75,
        'heading_h1': 'SURGE Water Analytic',
        'heading_issues': 'Good single H1',
        'missing_alt_count': 1,
        'meta_title': 'SURGE-Water Analytic - Suriota', 'meta_title_length': 30,
        'meta_desc': 'SaaS · Water Quality99.9% Uptime SLA SURGE-Water Analytic Built For Water treatment...', 'meta_desc_length': 423,
        'schema_types': 'FAQPage',
        'console_errors': 2,
        'critical_issues': 'Slow load: 10387ms; Meta desc 423 chars; Title 30 chars; 1 image missing alt',
        'warnings': 'Title 30 chars; Desc 423 chars; Missing alt; Load time 10.4s',
        'recommendations': 'Expand title; Truncate meta desc; Add alt text; Optimize load',
        'screenshots': 'screenshots/audit-cluster3-2026-05-18/'
    },
    {
        'page_id': 1740, 'page_name': 'ISO-M485 SERIES', 'url': 'https://suriota.com/iso-m485-series/',
        'design_score': 25, 'mobile_score': 12, 'perf_score': 7, 'seo_score': 18, 'a11y_score': 8, 'content_score': 10, 'total_score': 80,
        'heading_h1': 'ISO M485 SERIES | ISO-M485 SERIES',
        'heading_issues': 'Duplicate H1',
        'missing_alt_count': 0,
        'meta_title': 'ISO-M485 SERIES - Suriota', 'meta_title_length': 28,
        'meta_desc': 'Industrial Isolated RS-485 Transceiver Modules99.9% Uptime SLA ISO-M485 SERIES Built For...', 'meta_desc_length': 417,
        'schema_types': 'FAQPage',
        'console_errors': 2,
        'critical_issues': 'Slow load: 10105ms; Meta desc 417 chars; Title 28 chars; Duplicate H1',
        'warnings': 'Title 28 chars; Desc 417 chars; Duplicate H1; Load time 10.1s',
        'recommendations': 'Expand title; Truncate meta desc; Fix duplicate H1; Optimize load',
        'screenshots': 'screenshots/audit-cluster3-2026-05-18/'
    },
    {
        'page_id': 1741, 'page_name': 'THM-30MD', 'url': 'https://suriota.com/thm-30md/',
        'design_score': 25, 'mobile_score': 12, 'perf_score': 7, 'seo_score': 18, 'a11y_score': 8, 'content_score': 10, 'total_score': 80,
        'heading_h1': 'THM 30MD | THM-30MD',
        'heading_issues': 'Duplicate H1',
        'missing_alt_count': 0,
        'meta_title': 'THM-30MD - Suriota', 'meta_title_length': 21,
        'meta_desc': 'Industrial Temperature & Humidity Monitoring99.9% Uptime SLA THM-30MD Built For Temperature...', 'meta_desc_length': 449,
        'schema_types': 'FAQPage',
        'console_errors': 2,
        'critical_issues': 'Slow load: 11058ms; Meta desc 449 chars; Title 21 chars; Duplicate H1',
        'warnings': 'Title 21 chars; Desc 449 chars; Duplicate H1; Load time 11.1s',
        'recommendations': 'Expand title; Truncate meta desc; Fix duplicate H1; Optimize load',
        'screenshots': 'screenshots/audit-cluster3-2026-05-18/'
    },
    {
        'page_id': 1742, 'page_name': 'PM1611-WD', 'url': 'https://suriota.com/pm1611-wd/',
        'design_score': 25, 'mobile_score': 12, 'perf_score': 7, 'seo_score': 18, 'a11y_score': 8, 'content_score': 10, 'total_score': 80,
        'heading_h1': 'PM1611 WD | PM1611-WD',
        'heading_issues': 'Duplicate H1',
        'missing_alt_count': 0,
        'meta_title': 'PM1611-WD - Suriota', 'meta_title_length': 22,
        'meta_desc': 'Industrial Power Meter with Water Detection99.9% Uptime SLA PM1611-WD Built For Power monitoring...', 'meta_desc_length': 441,
        'schema_types': 'FAQPage',
        'console_errors': 2,
        'critical_issues': 'Slow load: 14772ms; Meta desc 441 chars; Title 22 chars; Duplicate H1',
        'warnings': 'Title 22 chars; Desc 441 chars; Duplicate H1; Load time 14.8s',
        'recommendations': 'Expand title; Truncate meta desc; Fix duplicate H1; Optimize load',
        'screenshots': 'screenshots/audit-cluster3-2026-05-18/'
    },
    {
        'page_id': 1765, 'page_name': 'RS-485 Surge Protector', 'url': 'https://suriota.com/rs-485-surge-protector/',
        'design_score': 25, 'mobile_score': 12, 'perf_score': 7, 'seo_score': 18, 'a11y_score': 8, 'content_score': 10, 'total_score': 80,
        'heading_h1': 'RS 485 Surge Protector | RS-485 Surge Protector',
        'heading_issues': 'Duplicate H1',
        'missing_alt_count': 0,
        'meta_title': 'RS-485 Surge Protector SPD-T485-105 | SURIOTA', 'meta_title_length': 45,
        'meta_desc': 'Industrial RS-485 Surge Protection99.9% Uptime SLA RS-485 Surge Protector Built For Surge protection...', 'meta_desc_length': 426,
        'schema_types': 'FAQPage',
        'console_errors': 2,
        'critical_issues': 'Slow load: 10940ms; Meta desc 426 chars; Title 45 chars (good); Duplicate H1',
        'warnings': 'Title 45 chars (good); Desc 426 chars; Duplicate H1; Load time 10.9s',
        'recommendations': 'Truncate meta desc; Fix duplicate H1; Optimize load',
        'screenshots': 'screenshots/audit-cluster3-2026-05-18/'
    },
    {
        'page_id': 839, 'page_name': 'Portfolio', 'url': 'https://suriota.com/portfolio/',
        'design_score': 20, 'mobile_score': 12, 'perf_score': 8, 'seo_score': 15, 'a11y_score': 7, 'content_score': 8, 'total_score': 70,
        'heading_h1': 'Portfolio | Portfolio',
        'heading_issues': 'Duplicate H1',
        'missing_alt_count': 0,
        'meta_title': 'Portfolio - Suriota', 'meta_title_length': 19,
        'meta_desc': None, 'meta_desc_length': 0,
        'schema_types': 'BreadcrumbList,Organization,WebPage,WebSite',
        'console_errors': 2,
        'critical_issues': 'Slow load: 7620ms; Duplicate H1; Missing meta description; Title only 19 chars',
        'warnings': 'Duplicate H1; No meta description; Title 19 chars; Thin content',
        'recommendations': 'Fix duplicate H1; Write meta description (150-160 chars); Expand title; Add portfolio description',
        'screenshots': 'screenshots/audit-cluster4/'
    },
    {
        'page_id': 1127, 'page_name': 'Internship', 'url': 'https://suriota.com/internship/',
        'design_score': 22, 'mobile_score': 13, 'perf_score': 9, 'seo_score': 15, 'a11y_score': 8, 'content_score': 8, 'total_score': 75,
        'heading_h1': 'Internship | Build Your Tech Career with SURIOTA',
        'heading_issues': 'Duplicate H1',
        'missing_alt_count': 0,
        'meta_title': 'Internship - Suriota', 'meta_title_length': 21,
        'meta_desc': 'Internship Program Batch 3 · Now Open Build Your Tech Career with SURIOTA...', 'meta_desc_length': 280,
        'schema_types': 'BreadcrumbList,Organization,WebPage,WebSite',
        'console_errors': 2,
        'critical_issues': 'Slow load: 6505ms; Duplicate H1; Meta desc 280 chars (too long); Title 21 chars',
        'warnings': 'Duplicate H1; Title 21 chars; Desc 280 chars',
        'recommendations': 'Fix duplicate H1; Expand title; Truncate meta desc',
        'screenshots': 'screenshots/audit-cluster4/'
    },
    {
        'page_id': 5029, 'page_name': 'Internet of Things', 'url': 'https://suriota.com/internet-of-things/',
        'design_score': 20, 'mobile_score': 10, 'perf_score': 8, 'seo_score': 10, 'a11y_score': 7, 'content_score': 7, 'total_score': 62,
        'heading_h1': 'Industrial Internet of Things',
        'heading_issues': 'Good single H1',
        'missing_alt_count': 0,
        'meta_title': 'Internet of Things - Suriota', 'meta_title_length': 29,
        'meta_desc': 'Industrial Internet of ThingsConnect, monitor, and optimise your industrial assets...', 'meta_desc_length': 400,
        'schema_types': 'BreadcrumbList,Organization,WebPage,WebSite',
        'console_errors': 2,
        'critical_issues': 'Slow load; Meta desc massive (auto-generated from content); Title 29 chars',
        'warnings': 'Title 29 chars; Desc ~400 chars (too long); Auto-generated desc includes nav breadcrumbs',
        'recommendations': 'Expand title; Write custom meta description; Do not use auto-generated descriptions',
        'screenshots': 'N/A'
    },
    {
        'page_id': 5031, 'page_name': 'System Integration', 'url': 'https://suriota.com/system-integration/',
        'design_score': 20, 'mobile_score': 10, 'perf_score': 8, 'seo_score': 10, 'a11y_score': 7, 'content_score': 7, 'total_score': 62,
        'heading_h1': 'System Integration',
        'heading_issues': 'Good single H1',
        'missing_alt_count': 0,
        'meta_title': 'System Integration - Suriota', 'meta_title_length': 29,
        'meta_desc': 'System IntegrationBridge SCADA, ERP, MES, and IoT into a single source of truth...', 'meta_desc_length': 400,
        'schema_types': 'BreadcrumbList,Organization,WebPage,WebSite',
        'console_errors': 2,
        'critical_issues': 'Slow load; Meta desc massive; Title 29 chars',
        'warnings': 'Title 29 chars; Desc ~400 chars; Auto-generated desc',
        'recommendations': 'Expand title; Write custom meta description',
        'screenshots': 'N/A'
    },
]

for page in pages:
    c.execute('''INSERT INTO page_scores 
        (page_id, page_name, url, design_score, mobile_score, perf_score, seo_score, a11y_score, content_score, total_score,
         heading_h1, heading_issues, missing_alt_count, meta_title, meta_title_length, meta_desc, meta_desc_length,
         schema_types, console_errors, critical_issues, warnings, recommendations, screenshots)
        VALUES (:page_id, :page_name, :url, :design_score, :mobile_score, :perf_score, :seo_score, :a11y_score, :content_score, :total_score,
                :heading_h1, :heading_issues, :missing_alt_count, :meta_title, :meta_title_length, :meta_desc, :meta_desc_length,
                :schema_types, :console_errors, :critical_issues, :warnings, :recommendations, :screenshots)''', page)

conn.commit()
conn.close()
print(f"Inserted {len(pages)} rows")
