import sqlite3

data = [
(12, 'Homepage', 'https://suriota.com/', 20, 12, 8, 15, 7, 8, 70, 'Homepage | Next Gen. Industrial Partner', 'Duplicate H1: entry-title + elementor heading', 3, 'Suriota - Surya Inovasi Prioritas', 39, 'PT Surya Inovasi Prioritas atau Suriota merupakan sebuah perusahaan yang bergerak di Technology Engineering Service berlokasi di Batam.', 132, 'BreadcrumbList,Organization,WebPage,WebSite', 2, 'Slow load: 8785ms; Tawk.to CORS error', 'Duplicate H1; 3 images missing alt; Meta desc could be more compelling; Only 259 words', 'Fix duplicate H1 by hiding entry-title; Add alt text to surge-eco-poster, modbus-poster, Porto.jpg; Expand homepage content to 400+ words; Optimize images', 'screenshots/audit-2026-05-18/'),
(29, 'About Us', 'https://suriota.com/about-us/', 22, 13, 10, 12, 8, 8, 73, 'About Us | About SURIOTA', 'Duplicate H1; Empty H2/H3 tags', 0, 'About Us - Suriota', 19, 'About SURIOTA Next Gen. Industrial Partner — Industrial IoT & System Integration in Batam, Indonesia 01 / VISION...', 330, 'BreadcrumbList,Organization,WebPage,WebSite', 2, 'Slow load: 4715ms; Meta desc 330 chars (way too long); Tawk.to CORS error', 'Duplicate H1; Meta description 330 chars (max 160); Empty heading tags; Only 276 words', 'Fix duplicate H1; Truncate meta desc to 150-160 chars; Remove empty heading tags; Add more content', 'screenshots/audit-2026-05-18/'),
(376, 'Tentang', 'https://suriota.com/tentang/', 5, 5, 5, 5, 5, 5, 30, 'Halaman tidak dapat ditemukan.', 'Page returns 404', 0, 'Laman tidak ditemukan – Suriota', 37, None, 0, 'None', 2, 'PAGE NOT FOUND (404); Page exists in WP but not accessible', 'Page is published but returns 404; Very old (2024-08-11); Likely slug/permalink issue', 'Investigate permalink/slug; Redirect to About Us or fix page; Remove from nav if dead', 'screenshots/audit-2026-05-18/'),
(33, 'Desain Grafis', 'https://suriota.com/desain-grafis/', 15, 10, 10, 10, 7, 6, 58, 'Desain Grafis | DESAIN GRAFIS', 'Duplicate H1; Very short title (23 chars)', 0, 'Desain Grafis - Suriota', 23, 'DESAIN GRAFIS Mewujudkan Visi Anda dengan Desain Grafis Memukau dari Suriota...', 380, 'BreadcrumbList,Organization,WebPage,WebSite', 2, 'Slow load: 6545ms; Meta desc 380 chars (too long); Title too short', 'Duplicate H1; Title only 23 chars; Description 380 chars; Low content (1644 chars)', 'Rewrite title to 50-60 chars; Truncate meta desc; Merge with main service or improve content', 'screenshots/audit-cluster2-2026-05-18/'),
(35, 'Automation', 'https://suriota.com/automation/', 23, 13, 10, 20, 8, 8, 82, 'Automation Services | Automation & IoT Services', 'Duplicate H1', 0, 'Industrial Automation & IoT Services | SURIOTA SCADA PLC', 60, 'PLC, SCADA, IIoT integration & SURGE platform for Industry 4.0. SURIOTA delivers industrial automation solutions across Indonesia.', 134, 'BreadcrumbList,Organization,WebPage,WebSite,Service,FAQPage', 2, 'Duplicate H1; Tawk.to CORS error', 'Duplicate H1; Good schema (Service + FAQPage)', 'Fix duplicate H1; Keep meta as-is (good length)', 'screenshots/audit-cluster2-2026-05-18/'),
(37, 'Electrical', 'https://suriota.com/electrical/', 22, 12, 3, 20, 8, 8, 73, 'Electrical Services | Electrical Services', 'Duplicate H1', 0, 'Industrial Electrical Engineering Services Batam | SURIOTA', 58, 'Panel installation, power distribution, commissioning & testing per SNI, IEC, PUIL.', 159, 'BreadcrumbList,Organization,WebPage,WebSite,Service,FAQPage', 2, 'EXTREMELY SLOW: 31686ms (31.7 seconds!); Duplicate H1; Tawk.to CORS', 'Load time 31.7s - critical performance issue; Duplicate H1', 'URGENT: Investigate why Electrical loads in 31s (image? script?); Fix duplicate H1; This is a revenue-critical page', 'screenshots/audit-cluster2-2026-05-18/'),
(39, 'Renewable Energy', 'https://suriota.com/renewable-energy/', 22, 12, 8, 20, 8, 8, 78, 'Renewable Energy Services | Renewable Energy Services', 'Duplicate H1', 0, 'Renewable Energy & Solar Panel Services | SURIOTA Indonesia', 60, 'Solar PV, hybrid PLTS-PLTB, energy audits & EPC. SURIOTA delivers renewable energy solutions.', 136, 'BreadcrumbList,Organization,WebPage,WebSite,Service,FAQPage', 2, 'Slow load: 10908ms; Duplicate H1', 'Duplicate H1; Load time 10.9s', 'Fix duplicate H1; Optimize page load (likely large images)', 'screenshots/audit-cluster2-2026-05-18/'),
(41, 'Teknologi Informasi', 'https://suriota.com/teknologi-informasi/', 18, 10, 7, 12, 7, 6, 60, 'Teknologi Informasi | TEKNOLOGI INFORMASI', 'Duplicate H1; Very short title (29 chars)', 0, 'Teknologi Informasi - Suriota', 29, 'TEKNOLOGI INFORMASI Layanan Teknologi Informasi Terbaik di Suriota...', 419, 'BreadcrumbList,Organization,WebPage,WebSite', 2, 'Slow load: 12557ms; Meta desc 419 chars (too long); Title too short', 'Duplicate H1; Title 29 chars; Desc 419 chars; Thin content', 'Rewrite title to 50-60 chars; Truncate meta desc; Expand content significantly', 'screenshots/audit-cluster2-2026-05-18/'),
(945, 'Water Treatment', 'https://suriota.com/water-treatment/', 22, 13, 10, 20, 8, 8, 81, 'Water Treatment Services', 'Only 1 H1 - good!', 0, 'Water Treatment & Wastewater Services | SURIOTA Indonesia', 58, 'Industrial water treatment, wastewater processing & IoT monitoring.', 134, 'BreadcrumbList,Organization,WebPage,WebSite,Service,FAQPage', 2, 'Slow load: 4794ms; Tawk.to CORS', 'Only 1 H1 (good!); Good meta lengths; Good schema', 'Optimize images to reduce load time; Keep structure as reference for other pages', 'screenshots/audit-cluster2-2026-05-18/'),
(934, 'Modbus Gateway', 'https://suriota.com/modbus-gateway/', 5, 5, 5, 5, 5, 5, 30, 'Halaman tidak dapat ditemukan.', 'PAGE NOT FOUND (404)', 0, 'Laman tidak ditemukan – Suriota', 37, None, 0, 'None', 2, 'PAGE NOT FOUND (404); Page exists in Elementor but not accessible; Load time 10666ms', 'Page is published in WP/Elementor but returns 404; URL slug may have changed', 'CRITICAL: Fix permalink/slug for Modbus Gateway; This is a flagship product page', 'screenshots/audit-cluster3-2026-05-18/'),
(929, 'Waste Water Loger', 'https://suriota.com/waste-water-loger/', 5, 5, 5, 5, 5, 5, 30, 'Halaman tidak dapat ditemukan.', 'PAGE NOT FOUND (404)', 0, 'Laman tidak ditemukan – Suriota', 37, None, 0, 'None', 2, 'PAGE NOT FOUND (404); Page exists in Elementor but not accessible', 'Page is published in WP/Elementor but returns 404', 'CRITICAL: Fix permalink/slug for Waste Water Loger', 'screenshots/audit-cluster3-2026-05-18/'),
(1542, 'SURGE-Energy Mapping', 'https://suriota.com/surge-energy-mapping/', 23, 12, 7, 18, 5, 10, 75, 'SURGE Energy Mapping', 'Good single H1', 1, 'SURGE-Energy Mapping - Suriota', 30, 'SaaS · Energy Monitoring99.9% Uptime SLA SURGE-Energy Mapping Built For Multi-location...', 453, 'FAQPage', 2, 'Slow load: 12444ms; Meta desc 453 chars (too long); Title too short (30 chars); 1 image missing alt', 'Title 30 chars; Desc 453 chars; Missing alt on product image; Load time 12.4s', 'Expand title to 50-60 chars; Truncate meta desc to 150-160; Add alt text to product image; Optimize load', 'screenshots/audit-cluster3-2026-05-18/'),
(1546, 'SURGE-Vessel Tracking', 'https://suriota.com/surge-vessel-tracking/', 23, 12, 7, 18, 5, 10, 75, 'SURGE Vessel Tracking', 'Good single H1', 1, 'SURGE-Vessel Tracking - Suriota', 31, 'SaaS · Vessel Tracking99.9% Uptime SLA SURGE-Vessel Tracking Built For Fleet tracking...', 429, 'FAQPage', 2, 'Slow load: 14659ms; Meta desc 429 chars; Title 31 chars; 1 image missing alt', 'Title 31 chars; Desc 429 chars; Missing alt; Load time 14.7s', 'Expand title; Truncate meta desc; Add alt text; Optimize load', 'screenshots/audit-cluster3-2026-05-18/'),
(1547, 'SURGE-Water Analytic', 'https://suriota.com/surge-water-analytic/', 23, 12, 7, 18, 5, 10, 75, 'SURGE Water Analytic', 'Good single H1', 1, 'SURGE-Water Analytic - Suriota', 30, 'SaaS · Water Quality99.9% Uptime SLA SURGE-Water Analytic Built For Water treatment...', 423, 'FAQPage', 2, 'Slow load: 10387ms; Meta desc 423 chars; Title 30 chars; 1 image missing alt', 'Title 30 chars; Desc 423 chars; Missing alt; Load time 10.4s', 'Expand title; Truncate meta desc; Add alt text; Optimize load', 'screenshots/audit-cluster3-2026-05-18/'),
(1740, 'ISO-M485 SERIES', 'https://suriota.com/iso-m485-series/', 25, 12, 7, 18, 8, 10, 80, 'ISO M485 SERIES | ISO-M485 SERIES', 'Duplicate H1', 0, 'ISO-M485 SERIES - Suriota', 28, 'Industrial Isolated RS-485 Transceiver Modules99.9% Uptime SLA ISO-M485 SERIES Built For...', 417, 'FAQPage', 2, 'Slow load: 10105ms; Meta desc 417 chars; Title 28 chars; Duplicate H1', 'Title 28 chars; Desc 417 chars; Duplicate H1; Load time 10.1s', 'Expand title; Truncate meta desc; Fix duplicate H1; Optimize load', 'screenshots/audit-cluster3-2026-05-18/'),
(1741, 'THM-30MD', 'https://suriota.com/thm-30md/', 25, 12, 7, 18, 8, 10, 80, 'THM 30MD | THM-30MD', 'Duplicate H1', 0, 'THM-30MD - Suriota', 21, 'Industrial Temperature & Humidity Monitoring99.9% Uptime SLA THM-30MD Built For Temperature...', 449, 'FAQPage', 2, 'Slow load: 11058ms; Meta desc 449 chars; Title 21 chars; Duplicate H1', 'Title 21 chars; Desc 449 chars; Duplicate H1; Load time 11.1s', 'Expand title; Truncate meta desc; Fix duplicate H1; Optimize load', 'screenshots/audit-cluster3-2026-05-18/'),
(1742, 'PM1611-WD', 'https://suriota.com/pm1611-wd/', 25, 12, 7, 18, 8, 10, 80, 'PM1611 WD | PM1611-WD', 'Duplicate H1', 0, 'PM1611-WD - Suriota', 22, 'Industrial Power Meter with Water Detection99.9% Uptime SLA PM1611-WD Built For Power monitoring...', 441, 'FAQPage', 2, 'Slow load: 14772ms; Meta desc 441 chars; Title 22 chars; Duplicate H1', 'Title 22 chars; Desc 441 chars; Duplicate H1; Load time 14.8s', 'Expand title; Truncate meta desc; Fix duplicate H1; Optimize load', 'screenshots/audit-cluster3-2026-05-18/'),
(1765, 'RS-485 Surge Protector', 'https://suriota.com/rs-485-surge-protector/', 25, 12, 7, 18, 8, 10, 80, 'RS 485 Surge Protector | RS-485 Surge Protector', 'Duplicate H1', 0, 'RS-485 Surge Protector SPD-T485-105 | SURIOTA', 45, 'Industrial RS-485 Surge Protection99.9% Uptime SLA RS-485 Surge Protector Built For Surge protection...', 426, 'FAQPage', 2, 'Slow load: 10940ms; Meta desc 426 chars; Title 45 chars (good); Duplicate H1', 'Title 45 chars (good); Desc 426 chars; Duplicate H1; Load time 10.9s', 'Truncate meta desc; Fix duplicate H1; Optimize load', 'screenshots/audit-cluster3-2026-05-18/'),
(839, 'Portfolio', 'https://suriota.com/portfolio/', 20, 12, 8, 15, 7, 8, 70, 'Portfolio | Portfolio', 'Duplicate H1', 0, 'Portfolio - Suriota', 19, None, 0, 'BreadcrumbList,Organization,WebPage,WebSite', 2, 'Slow load: 7620ms; Duplicate H1; Missing meta description; Title only 19 chars', 'Duplicate H1; No meta description; Title 19 chars; Thin content', 'Fix duplicate H1; Write meta description (150-160 chars); Expand title; Add portfolio description', 'screenshots/audit-cluster4/'),
(1127, 'Internship', 'https://suriota.com/internship/', 22, 13, 9, 15, 8, 8, 75, 'Internship | Build Your Tech Career with SURIOTA', 'Duplicate H1', 0, 'Internship - Suriota', 21, 'Internship Program Batch 3 · Now Open Build Your Tech Career with SURIOTA...', 280, 'BreadcrumbList,Organization,WebPage,WebSite', 2, 'Slow load: 6505ms; Duplicate H1; Meta desc 280 chars (too long); Title 21 chars', 'Duplicate H1; Title 21 chars; Desc 280 chars', 'Fix duplicate H1; Expand title; Truncate meta desc', 'screenshots/audit-cluster4/'),
(5029, 'Internet of Things', 'https://suriota.com/internet-of-things/', 20, 10, 8, 10, 7, 7, 62, 'Industrial Internet of Things', 'Good single H1', 0, 'Internet of Things - Suriota', 29, 'Industrial Internet of ThingsConnect, monitor, and optimise your industrial assets...', 400, 'BreadcrumbList,Organization,WebPage,WebSite', 2, 'Slow load; Meta desc massive (auto-generated from content); Title 29 chars', 'Title 29 chars; Desc ~400 chars (too long); Auto-generated desc includes nav breadcrumbs', 'Expand title; Write custom meta description; Do not use auto-generated descriptions', 'N/A'),
(5031, 'System Integration', 'https://suriota.com/system-integration/', 20, 10, 8, 10, 7, 7, 62, 'System Integration', 'Good single H1', 0, 'System Integration - Suriota', 29, 'System IntegrationBridge SCADA, ERP, MES, and IoT into a single source of truth...', 400, 'BreadcrumbList,Organization,WebPage,WebSite', 2, 'Slow load; Meta desc massive; Title 29 chars', 'Title 29 chars; Desc ~400 chars; Auto-generated desc', 'Expand title; Write custom meta description', 'N/A'),
]

conn = sqlite3.connect('website_audit.db')
c = conn.cursor()
for row in data:
    c.execute('''INSERT INTO page_scores 
        (page_id, page_name, url, design_score, mobile_score, perf_score, seo_score, a11y_score, content_score, total_score,
         heading_h1, heading_issues, missing_alt_count, meta_title, meta_title_length, meta_desc, meta_desc_length,
         schema_types, console_errors, critical_issues, warnings, recommendations, screenshots)
        VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)''', row)
conn.commit()
conn.close()
print(f"Inserted {len(data)} rows")
